import express from "express";
import { registerDashBoardAdmin } from "./admin/getDashBoardStats";
import { registerRecentOrders } from "./admin/getRecentOrders";
import { registerGetCustomers } from "./admin/getCustomer";
import { registerCreateProduct } from "./admin/createProduct";
import { registerGetProduct } from "./admin/getProduct";
import { registerGetProductItem } from "./admin/getProductItem";
import { registerOrderRoutes } from "./admin/getOrders";
import { registerGetOrdersDetail } from "./admin/getOrdersDetail";
import { registerUpdateOrderStatus } from "./admin/updateOrderStatus";
import { registerGetPurchaseOrders } from "./admin/getPurchaseOrders";
import { registerGetPurchaseOrderDetail } from "./admin/getPurchaseOrderDetail";
import { registerCreatePurchaseOrder } from "./admin/createPurchaseOrder";
import { registerGetSuppliers } from "./admin/getSuppliers";
import { registerGetEmployees } from "./admin/getEmployees";
import { registerGetCategories } from "./admin/getCategories";
import { registerGetTopSellingProducts } from "./admin/getTopSellingProducts";
import { registerUpdateProduct } from "./admin/updateProduct";
import { registerDeleteProduct } from "./admin/deleteProduct";
import { registerGetInvoices } from "./admin/getInvoices";
const router = express.Router();
registerDashBoardAdmin(router);
registerRecentOrders(router);
registerGetCustomers(router);
registerCreateProduct(router);
registerGetProduct(router);
registerGetProductItem(router);
registerOrderRoutes(router);
registerGetOrdersDetail(router);
registerUpdateOrderStatus(router);
registerGetPurchaseOrders(router);
registerGetPurchaseOrderDetail(router);
registerCreatePurchaseOrder(router);
registerGetSuppliers(router);
registerGetEmployees(router);
registerGetCategories(router);
registerGetTopSellingProducts(router);
registerUpdateProduct(router);
registerDeleteProduct(router);
registerGetInvoices(router);

export default router;
