import express from "express";
import { registerDashBoardAdmin } from "./admin/getDashBoardStats";
import { registerRecentOrders } from "./admin/getRecentOrders";
import { registerGetCustomers } from "./admin/getCustomer"; 
import { registerCreateProduct } from "./admin/createProduct";
import { registerGetProduct } from "./admin/getProduct";
import { registerGetProductItem } from "./admin/getProductItem";
import { registerOrderRoutes } from "./admin/getOrders";
import { registerGetOrdersDetail } from "./admin/getOrdersDetail";
import { registerUpdateOrderStatus } from "./admin/updateOrderStatus";
import { register } from "module";
const router = express.Router();
registerDashBoardAdmin(router);
registerRecentOrders(router);
registerGetCustomers(router);
// registerCreateProduct(router);
registerGetProduct(router);
registerGetProductItem(router);
registerOrderRoutes(router);
registerGetOrdersDetail(router);
registerUpdateOrderStatus(router);

export default router;
